spring:
  datasource:
    url: jdbc:postgresql://10.10.17.10:5432/postgres
    username: '{cipher}1d995a3cf78b65424e93236da7955bc75f8498f9a95e4f49803e749b85cd049f'
    password: '{cipher}1d995a3cf78b65424e93236da7955bc75f8498f9a95e4f49803e749b85cd049f'
  jpa:
    properties:
      hibernate.dialect: biz.ep.proc.front.conf.HibernatePostgresDialect
      hibernate.jdbc.lob.non_contextual_creation: true
