spring:
  jpa:
    properties:
      hibernate.dialect: biz.ep.proc.back.HibernatePostgresDialect
  mail:
    default-encoding: utf-16
    host: smtp.yandex.ru
    port: 465
    username: 'billinger@ribank.ru'
    password: '1qaz!QAZ'
    protocol: smtp
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


logging:
  file: /var/log/backServer.log
  path: /var/log/

server.port: 8083

#Очередь которую прослушивает фронт, для получения статуса авторизации
back:
  poller:
    pool.size: 20
    fixedDelay: 100
    max.message: 100
  first:
  script:
    #От какого имени будем оптарвлять почту
    email.from: 'reestr@europlat.biz'
    path:
      php: '/bin/php'
      python: '/bin/python'
      roots:
        - '/opt/script'
