spring:
  jpa:
    properties:
      hibernate.dialect: biz.ep.proc.back.database.core.HibernatePostgresDialect


logging:
  file: /opt/service/jsonapi/log/jsonapi.log
  path: /opt/service/jsonapi/log/

server.port: 8082
